# Generated by Django 3.2.25 on 2024-04-16 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveBigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField()),
                ('selected_seats_display', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.storageuserdup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.warehouse')),
                ('warehouse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.warehousetype')),
            ],
        ),
    ]
